Repository CH4-IS20/delivery-system, pull requests merged in 2024-09, with the labels that each got.

#3 Build: eureka 초기 세팅 추가
  eureka/.gitignore
  eureka/build.gradle
  eureka/gradle/wrapper/gradle-wrapper.jar
  eureka/gradle/wrapper/gradle-wrapper.properties
  eureka/gradlew
  eureka/gradlew.bat
  eureka/settings.gradle
  eureka/src/main/java/eureka/EurekaApplication.java
  eureka/src/main/resources/application-dev.yml
  eureka/src/main/resources/application-prod.yml
  eureka/src/main/resources/application.yml
  eureka/src/test/java/eureka/EurekaApplicationTests.java
Labels: feature

#7 Fix: spring-boot-starter-web 의존성 추가
  eureka/build.gradle
Labels: fix

#8 Feat: 업체 & 상품 프로젝트 생성, API 기능을 위한 파일 작성 및 Create, Read 구현
  .gitignore
  company/.gitignore
  company/Dockerfile
  company/build.gradle
  company/docker-compose.yml
  company/gradle/wrapper/gradle-wrapper.jar
  company/gradle/wrapper/gradle-wrapper.properties
  company/gradlew
  company/gradlew.bat
  company/settings.gradle
  company/src/main/java/com/sparta/ch4/delivery/company/CompanyApplication.java
  company/src/main/java/com/sparta/ch4/delivery/company/application/dto/CompanyDto.java
  company/src/main/java/com/sparta/ch4/delivery/company/application/dto/ProductDto.java
  company/src/main/java/com/sparta/ch4/delivery/company/application/service/CompanyService.java
  company/src/main/java/com/sparta/ch4/delivery/company/application/service/ProductService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/model/BaseEntity.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/model/Company.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/model/Product.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/repository/CompanyRepositoryCustom.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/repository/ProductRepository.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/repository/ProductRepositoryCustom.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/service/CompanyDomainService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/service/ProductDomainService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/type/CompanyType.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/client/HubClient.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/config/JpaConfig.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/repository/CompanyRepositoryCustomImpl.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/repository/ProductRepositoryCustomImpl.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/controller/CompanyController.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/controller/ProductController.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/request/CompanyCreateRequest.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/request/ProductCreateRequest.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/response/CommonResponse.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/response/CompanyResponse.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/response/ProductResponse.java
  company/src/main/resources/application-dev.yml
  company/src/main/resources/application-local.yml
  company/src/main/resources/application.yml
  company/src/test/java/com/sparta/ch4/delivery/company/CompanyApplicationTests.java
Labels: feature

#10 Feature: User 서버 초기 설정 추가
  user/.gitignore
  user/Dockerfile
  user/build.gradle
  user/docker-compose.yml
  user/gradle/wrapper/gradle-wrapper.jar
  user/gradle/wrapper/gradle-wrapper.properties
  user/gradlew
  user/gradlew.bat
  user/settings.gradle
  user/src/main/java/com/sparta/ch4/delivery/user/UserApplication.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/model/BaseEntity.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/model/User.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/type/UserRole.java
  user/src/main/resources/application-dev.yml
  user/src/main/resources/application-local.yml
  user/src/main/resources/application.yml
  user/src/test/java/com/sparta/ch4/delivery/user/UserApplicationTests.java
Labels: feature, Size:L, Priority:HIGH

#14 Feat: 업체 API의 CRUD, Search 를 작성
  company/src/main/java/com/sparta/ch4/delivery/company/CompanyApplication.java
  company/src/main/java/com/sparta/ch4/delivery/company/application/service/CompanyService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/repository/CompanyRepositoryCustom.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/service/CompanyDomainService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/type/CompanySearchType.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/repository/CompanyRepositoryCustomImpl.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/controller/CompanyController.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/request/CompanyUpdateRequest.java
Labels: feature, refactor

#16 Feat: 상품 API의 CRUD, Search 를 작성, Test 코드 작성
  company/src/main/java/com/sparta/ch4/delivery/company/application/dto/CompanyDto.java
  company/src/main/java/com/sparta/ch4/delivery/company/application/dto/ProductDto.java
  company/src/main/java/com/sparta/ch4/delivery/company/application/service/ProductService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/repository/ProductRepositoryCustom.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/service/CompanyDomainService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/service/ProductDomainService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/type/ProductSearchType.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/repository/ProductRepositoryCustomImpl.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/controller/CompanyController.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/controller/ProductController.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/request/ProductUpdateRequest.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/response/ProductResponse.java
  company/src/test/java/com/sparta/ch4/delivery/company/application/service/ProductServiceTest.java
  company/src/test/java/com/sparta/ch4/delivery/company/presentation/controller/ProductControllerTest.java
Labels: feature, refactor

#19 Feat: 사용자 CRUD Api 구현
  user/build.gradle
  user/src/main/java/com/sparta/ch4/delivery/user/UserApplication.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/dto/RegisterDto.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/dto/UserDto.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/dto/UserPageDto.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/dto/UserUpdateDto.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/service/AuthService.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/service/UserService.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/model/User.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/repository/UserPageRepository.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/repository/UserRepository.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/service/UserDomainService.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/type/UserRole.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/type/UserSearchType.java
  user/src/main/java/com/sparta/ch4/delivery/user/infrastructure/config/JpaConfig.java
  user/src/main/java/com/sparta/ch4/delivery/user/infrastructure/config/SecurityConfig.java
  user/src/main/java/com/sparta/ch4/delivery/user/infrastructure/repository/UserPageRepositoryImpl.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/controller/AuthController.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/controller/UserController.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/LoginRequest.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/RegisterRequest.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/UserUpdateRequest.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/response/CommonResponse.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/response/UserResponse.java
Labels: feature, Size:L, Priority:HIGH

#21 Feature/#18 hub api
  hub/Dockerfile
  hub/build.gradle
  hub/src/main/java/com/example/hub/HubApplication.java
  hub/src/main/java/com/example/hub/application/dto/HubDto.java
  hub/src/main/java/com/example/hub/application/geocode/Geometry.java
  hub/src/main/java/com/example/hub/application/geocode/GoogleMapResponse.java
  hub/src/main/java/com/example/hub/application/geocode/Location.java
  hub/src/main/java/com/example/hub/application/geocode/Result.java
  hub/src/main/java/com/example/hub/application/service/HubService.java
  hub/src/main/java/com/example/hub/domain/exception/ApplicationException.java
  hub/src/main/java/com/example/hub/domain/exception/ErrorCode.java
  hub/src/main/java/com/example/hub/domain/exception/ErrorResponse.java
  hub/src/main/java/com/example/hub/domain/exception/ExceptionManager.java
  hub/src/main/java/com/example/hub/domain/model/BaseEntity.java
  hub/src/main/java/com/example/hub/domain/model/Hub.java
  hub/src/main/java/com/example/hub/domain/model/HubRoute.java
  hub/src/main/java/com/example/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/example/hub/domain/repository/HubRepositoryCustom.java
  hub/src/main/java/com/example/hub/domain/service/HubDomainService.java
  hub/src/main/java/com/example/hub/domain/type/HubAddress.java
  hub/src/main/java/com/example/hub/infrastructure/config/JpaConfig.java
  hub/src/main/java/com/example/hub/infrastructure/repository/HubRepositoryImpl.java
  hub/src/main/java/com/example/hub/presentation/config/SwaggerConfig.java
  hub/src/main/java/com/example/hub/presentation/controller/HubController.java
  hub/src/main/java/com/example/hub/presentation/request/HubCreateRequest.java
  hub/src/main/java/com/example/hub/presentation/response/CommonResponse.java
  hub/src/main/java/com/example/hub/presentation/response/HubResponse.java
  hub/src/main/resources/application-local.yml
  hub/src/main/resources/application.yml
Labels: feature, fix, Priority:HIGH

#23 Feat: 주문, 배송, 배송 기록 프로젝트 생성 및 엔티티 작성
  order/.gitignore
  order/Dockerfile
  order/build.gradle
  order/docker-compose.yml
  order/gradle/wrapper/gradle-wrapper.jar
  order/gradle/wrapper/gradle-wrapper.properties
  order/gradlew
  order/gradlew.bat
  order/settings.gradle
  order/src/main/java/com/sparta/ch4/delivery/order/OrderApplication.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/model/BaseEntity.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/model/Delivery.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/model/DeliveryHistory.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/model/Order.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/type/DeliveryStatus.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/type/OrderStatus.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/config/JpaConfig.java
  order/src/main/resources/application-dev.yml
  order/src/main/resources/application-local.yml
  order/src/main/resources/application.yml
  order/src/test/java/com/sparta/ch4/delivery/order/OrderApplicationTests.java
Labels: feature

#24 Feature/#20 implement login
  user/build.gradle
  user/docker-compose.yml
  user/src/main/java/com/sparta/ch4/delivery/user/application/dto/LoginDto.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/service/AuthService.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/repository/UserRepository.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/service/UserDomainService.java
  user/src/main/java/com/sparta/ch4/delivery/user/infrastructure/jwt/JwtTokenProvider.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/controller/AuthController.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/LoginRequest.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/response/UserResponse.java
  user/src/main/resources/application-dev.yml
  user/src/main/resources/application-local.yml
Labels: feature, Size:M, Priority:HIGH

#29 feat: User 엔티티에 slackId 추가
  user/src/main/java/com/sparta/ch4/delivery/user/application/dto/RegisterDto.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/dto/UserDto.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/dto/UserPageDto.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/dto/UserUpdateDto.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/model/User.java
  user/src/main/java/com/sparta/ch4/delivery/user/infrastructure/repository/UserPageRepositoryImpl.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/RegisterRequest.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/UserUpdateRequest.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/response/UserResponse.java
Labels: feature, Size:S, Priority:NORMAL

#30 build: Gateway 초기 설정 추가
  gateway/.gitignore
  gateway/Dockerfile
  gateway/build.gradle
  gateway/docker-compose.yml
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/gradlew.bat
  gateway/settings.gradle
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/GatewayApplication.java
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/security/JwtAuthenticationFilter.java
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/security/SecurityConfig.java
  gateway/src/main/resources/application-dev.yml
  gateway/src/main/resources/application-local.yml
  gateway/src/main/resources/application.yml
  gateway/src/test/java/com/sparta/ch4/delivery/gateway/GatewayApplicationTests.java
Labels: feature, Priority:LOW, Size:XL

#32 feat: User 서버에 Slack 엔티티 구현
  user/src/main/java/com/sparta/ch4/delivery/user/application/dto/SlackMessageDto.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/dto/UserUpdateDto.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/service/SlackService.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/model/Slack.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/model/User.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/repository/SlackPageRepository.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/repository/SlackRepository.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/service/SlackDomainService.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/type/SlackSearchType.java
  user/src/main/java/com/sparta/ch4/delivery/user/infrastructure/repository/SlackPageRepositoryImpl.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/controller/SlackController.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/SlackSendMessageRequest.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/UserUpdateRequest.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/response/SlackResponse.java
Labels: feature, Size:L, Priority:LOW

#28 Feat: 주문 프로세스 API(CRUD) 1차 작성
  company/src/main/java/com/sparta/ch4/delivery/company/application/dto/ProductDto.java
  company/src/main/java/com/sparta/ch4/delivery/company/application/service/CompanyService.java
  company/src/main/java/com/sparta/ch4/delivery/company/application/service/ProductService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/service/ProductDomainService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/type/ProductQuantity.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/type/UserRole.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/client/UserClient.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/client/response/UserResponse.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/controller/CompanyController.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/controller/ProductController.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/request/ProductQuantityUpdateRequest.java
  company/src/test/java/com/sparta/ch4/delivery/company/application/service/ProductServiceTest.java
  order/build.gradle
  order/src/main/java/com/sparta/ch4/delivery/order/OrderApplication.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/dto/DeliveryDto.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/dto/OrderDto.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/service/OrderService.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/model/Delivery.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/model/DeliveryHistory.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/model/Order.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/repository/DeliveryHistoryRepository.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/repository/DeliveryHistoryRepositoryCustom.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/repository/DeliveryRepository.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/repository/DeliveryRepositoryCustom.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/repository/OrderRepository.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/repository/OrderRepositoryCustom.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/service/DeliveryDomainService.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/service/DeliveryHistoryDomainService.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/service/OrderDomainService.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/type/CompanyType.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/type/OrderSearchType.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/type/ProductQuantity.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/client/CompanyClient.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/client/HubRouteClient.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/client/ProductClient.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/client/request/ProductQuantityUpdateRequest.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/client/request/ProductUpdateRequest.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/client/response/CompanyResponse.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/client/response/HubRouteForOrderResponse.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/client/response/ProductResponse.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/repository/OrderRepositoryCustomImpl.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/controller/OrderController.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/request/OrderCreateRequest.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/request/OrderUpdateRequest.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/response/CommonResponse.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/response/OrderResponse.java
  order/src/main/resources/application-local.yml
  order/src/test/java/com/sparta/ch4/delivery/order/application/service/OrderServiceTest.java
Labels: feature, refactor, Priority:HIGH

#36 Feat/#22 hub route api
  hub/src/main/java/com/example/hub/application/dto/EndHubRouteDto.java
  hub/src/main/java/com/example/hub/application/service/HubRoutService.java
  hub/src/main/java/com/example/hub/domain/exception/ErrorCode.java
  hub/src/main/java/com/example/hub/domain/exception/ErrorResponse.java
  hub/src/main/java/com/example/hub/domain/exception/ExceptionManager.java
  hub/src/main/java/com/example/hub/domain/model/Hub.java
  hub/src/main/java/com/example/hub/domain/model/HubRoute.java
  hub/src/main/java/com/example/hub/domain/naver/Location.java
  hub/src/main/java/com/example/hub/domain/naver/NaverResponse.java
  hub/src/main/java/com/example/hub/domain/naver/Route.java
  hub/src/main/java/com/example/hub/domain/naver/Summary.java
  hub/src/main/java/com/example/hub/domain/naver/Trafast.java
  hub/src/main/java/com/example/hub/domain/repository/HubRouteRepository.java
  hub/src/main/java/com/example/hub/domain/repository/HubRouteRepositoryCustom.java
  hub/src/main/java/com/example/hub/domain/service/HubRouteDomainService.java
  hub/src/main/java/com/example/hub/infrastructure/config/AppConfig.java
  hub/src/main/java/com/example/hub/presentation/controller/HubController.java
  hub/src/main/java/com/example/hub/presentation/controller/HubRouteController.java
  hub/src/main/java/com/example/hub/presentation/response/CommonResponse.java
  hub/src/main/java/com/example/hub/presentation/response/EndHubRouteResponse.java
  hub/src/main/java/com/example/hub/presentation/response/HubRouteResponse.java
  hub/src/main/resources/application-local.yml
  hub/src/test/java/com/example/hub/presentation/controller/HubControllerTest.java
  hub/src/test/java/com/example/hub/presentation/fixture/HubCreateRequestFixture.java
  hub/src/test/java/com/example/hub/presentation/fixture/HubFixture.java
Labels: Priority:HIGH

#39 Feat: add jwt filter gateway
  gateway/docker-compose.yml
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/security/JwtAuthenticationFilter.java
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/security/SecurityConfig.java
  gateway/src/main/resources/application-dev.yml
  gateway/src/main/resources/application-local.yml
Labels: feature

#43 Feat: Docker compose 작성 , Redis, 모니터링 컨테이너 추가
  build-docker-compose.sh
  company/src/main/resources/application-dev.yml
  config/prometheus.yml
  docker/docker-compose.cache.yml
  docker/docker-compose.company.yml
  docker/docker-compose.eureka.yml
  docker/docker-compose.gateway.yml
  docker/docker-compose.hub.yml
  docker/docker-compose.network.yml
  docker/docker-compose.order.yml
  docker/docker-compose.user.yml
  docker/docker.compose.monitor.yml
  eureka/Dockerfile
  eureka/src/main/resources/application-dev.yml
  eureka/src/main/resources/application-prod.yml
  hub/src/main/resources/application-dev.yml
  hub/src/main/resources/application-local.yml
  order/src/main/resources/application-dev.yml
  user/src/main/resources/application-dev.yml
Labels: feature, Size:M, Priority:NORMAL

#41 Feat: 배송 & 배송 기록 API 작성
  company/src/main/java/com/sparta/ch4/delivery/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/repository/ProductRepository.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/service/CompanyDomainService.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/repository/CompanyRepositoryCustom.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/repository/CompanyRepositoryCustomImpl.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/repository/ProductRepositoryCustom.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/repository/ProductRepositoryCustomImpl.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/dto/DeliveryDto.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/dto/DeliveryHistoryDto.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/dto/DeliveryStatusUpdateDto.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/dto/OrderCreateDto.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/dto/OrderDto.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/service/DeliveryHistoryService.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/service/DeliveryService.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/service/OrderService.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/model/DeliveryHistory.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/repository/DeliveryHistoryRepository.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/repository/DeliveryHistoryRepositoryCustom.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/repository/DeliveryRepository.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/repository/DeliveryRepositoryCustom.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/repository/OrderRepository.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/service/DeliveryDomainService.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/service/DeliveryHistoryDomainService.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/type/DeliverySearchType.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/repository/DeliveryHistoryRepositoryCustom.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/repository/DeliveryRepositoryCustom.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/repository/DeliveryRepositoryCustomImpl.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/repository/OrderRepositoryCustom.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/repository/OrderRepositoryCustomImpl.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/controller/DeliveryController.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/controller/DeliveryHistoryController.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/controller/OrderController.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/request/DeliveryHistoryStatusUpdateRequest.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/request/DeliveryStatusUpdateRequest.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/request/OrderCreateRequest.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/response/DeliveryHistoryResponse.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/response/DeliveryResponse.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/response/OrderResponse.java
  order/src/test/java/com/sparta/ch4/delivery/order/application/service/OrderServiceTest.java
Labels: feature, fix

#47 Feat: User 서버에 Swagger 설정 추가 및 예외 처리 핸들러 구현
  user/build.gradle
  user/src/main/java/com/sparta/ch4/delivery/user/application/service/AuthService.java
  user/src/main/java/com/sparta/ch4/delivery/user/application/service/SlackService.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/exception/ApplicationException.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/exception/ErrorCode.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/exception/ErrorResponse.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/exception/ExceptionManager.java
  user/src/main/java/com/sparta/ch4/delivery/user/domain/service/UserDomainService.java
  user/src/main/java/com/sparta/ch4/delivery/user/infrastructure/client/SlackMessageClient.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/config/SwaggerConfig.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/controller/AuthController.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/controller/SlackController.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/controller/UserController.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/LoginRequest.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/RegisterRequest.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/SlackSendMessageRequest.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/request/UserUpdateRequest.java
Labels: feature, Size:L

#49 Feat: 업체 & 상품 유저 권한 검증, swagger 연결, 테스트 코드 수정
  company/build.gradle
  company/src/main/java/com/sparta/ch4/delivery/company/application/service/CompanyService.java
  company/src/main/java/com/sparta/ch4/delivery/company/application/service/ProductService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/exception/ApplicationException.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/exception/ErrorCode.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/exception/ErrorResponse.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/exception/ExceptionManager.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/service/CompanyDomainService.java
  company/src/main/java/com/sparta/ch4/delivery/company/domain/service/ProductDomainService.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/client/HubClient.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/client/UserClient.java
  company/src/main/java/com/sparta/ch4/delivery/company/infrastructure/client/response/HubResponse.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/config/SwaggerConfig.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/controller/CompanyController.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/controller/ProductController.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/request/CompanyCreateRequest.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/request/CompanyUpdateRequest.java
  company/src/main/java/com/sparta/ch4/delivery/company/presentation/request/ProductQuantityUpdateRequest.java
  company/src/test/java/com/sparta/ch4/delivery/company/application/service/ProductServiceTest.java
Labels: feature, fix, refactor

#51 Feat: Swagger Gateway 통합
  company/src/main/resources/application-dev.yml
  company/src/main/resources/application-local.yml
  gateway/build.gradle
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/config/SwaggerConfig.java
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/security/SecurityConfig.java
  gateway/src/main/resources/application-dev.yml
  gateway/src/main/resources/application-local.yml
  hub/src/main/resources/application-dev.yml
  hub/src/main/resources/application-local.yml
  user/src/main/resources/application-dev.yml
  user/src/main/resources/application-local.yml
Labels: feature, Size:M, Priority:NORMAL

#54 fix: User 서버 gateway에 대한 CORS 설정 추가
  docker/docker-compose.user.yml
  user/src/main/java/com/sparta/ch4/delivery/user/infrastructure/config/SecurityConfig.java
  user/src/main/java/com/sparta/ch4/delivery/user/presentation/controller/AuthController.java
  user/src/main/resources/application-dev.yml
  user/src/main/resources/application-local.yml
Labels: fix, Priority:HIGH

#56 Fix: 각 서비스 별 Docker 및 프로필 재설정
  build-docker-compose.sh
  company/Dockerfile
  company/src/main/resources/application-dev.yml
  docker/docker-compose.cache.yml
  docker/docker-compose.company.yml
  docker/docker-compose.eureka.yml
  docker/docker-compose.gateway.yml
  docker/docker-compose.hub.yml
  docker/docker-compose.network.yml
  docker/docker-compose.order.yml
  docker/docker-compose.user.yml
  eureka/Dockerfile
  gateway/Dockerfile
  gateway/src/main/resources/application-dev.yml
  hub/Dockerfile
  hub/src/main/resources/application-dev.yml
  order/Dockerfile
  order/src/main/resources/application-dev.yml
  user/src/main/resources/application-dev.yml
Labels: feature, fix, Size:L, Priority:HIGH

#58 refactor: cors 설정 삭제
  docker/docker-compose.user.yml
  user/src/main/java/com/sparta/ch4/delivery/user/infrastructure/config/SecurityConfig.java
  user/src/main/resources/application-dev.yml
  user/src/main/resources/application-local.yml
Labels: refactor, Priority:LOW

#60 feat: gateway에 zipkin 설정 추가
  docker/docker-compose.gateway.yml
  docker/docker.compose.monitor.yml
  gateway/build.gradle
  gateway/src/main/resources/application-dev.yml
  gateway/src/main/resources/application-local.yml
Labels: feature, Priority:LOW

#61 Feat/#50 delivery manager api
  hub/src/main/java/com/example/hub/application/service/DeliveryManagerService.java
  hub/src/main/java/com/example/hub/domain/exception/ErrorCode.java
  hub/src/main/java/com/example/hub/domain/model/DeliveryManager.java
  hub/src/main/java/com/example/hub/domain/model/Hub.java
  hub/src/main/java/com/example/hub/domain/repository/DeliveryManagerRepository.java
  hub/src/main/java/com/example/hub/domain/repository/DeliveryManagerRepositoryCustom.java
  hub/src/main/java/com/example/hub/domain/service/DeliveryManagerDomainService.java
  hub/src/main/java/com/example/hub/domain/type/DeliveryManagerType.java
  hub/src/main/java/com/example/hub/domain/type/UserRole.java
  hub/src/main/java/com/example/hub/infrastructure/repository/DeliveryManagerRepositoryImpl.java
  hub/src/main/java/com/example/hub/presentation/controller/DeliveryManagerController.java
  hub/src/main/java/com/example/hub/presentation/request/DeliveryManagerCreateRequest.java
  hub/src/main/java/com/example/hub/presentation/response/DeliveryManagerResponse.java
Labels: feature

#64 Feat: 게이트웨이에서 `X-Role` 헤더 추가
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/security/JwtAuthenticationFilter.java
Labels: feature, Priority:HIGH

#67 fix: Docker 관련 수정
  build-boot.sh
  build-docker-compose.sh
  company/Dockerfile
  eureka/Dockerfile
  eureka/build.gradle
  gateway/Dockerfile
  gateway/build.gradle
  hub/Dockerfile
  order/Dockerfile
  order/build.gradle
  user/Dockerfile
Labels: feature, fix

#53 Feat: 정책 관리 서버 구현
  build-boot.sh
  build-docker-compose.sh
  docker/docker-compose.gateway.yml
  docker/docker-compose.policy.yml
  gateway/build.gradle
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/config/RedissonConfig.java
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/response/ErrorResponse.java
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/response/ResponseWriter.java
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/security/JwtAuthenticationFilter.java
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/security/RoleAuthorizationFilter.java
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/security/SecurityConfig.java
  gateway/src/main/resources/application-dev.yml
  gateway/src/main/resources/application-local.yml
  policy/.gitignore
  policy/Dockerfile
  policy/build.gradle
  policy/gradle/wrapper/gradle-wrapper.jar
  policy/gradle/wrapper/gradle-wrapper.properties
  policy/gradlew
  policy/gradlew.bat
  policy/settings.gradle
  policy/src/main/java/com/sparta/ch4/delivery/policy/PolicyApplication.java
  policy/src/main/java/com/sparta/ch4/delivery/policy/config/RedissonConfig.java
  policy/src/main/java/com/sparta/ch4/delivery/policy/controller/PolicyController.java
  policy/src/main/java/com/sparta/ch4/delivery/policy/service/PolicyService.java
  policy/src/main/resources/application-dev.yml
  policy/src/main/resources/application.yml
  policy/src/test/java/com/sparta/ch4/delivery/policy/PolicyApplicationTests.java
Labels: feature, Priority:NORMAL, Size:XL

#71 refactor: MASTER 권한은 필터 체인 통과
  gateway/src/main/java/com/sparta/ch4/delivery/gateway/security/RoleAuthorizationFilter.java
Labels: refactor

#75 fix: DeliveryManager Id 필드 타입 변경에 따른 에러 수정
  hub/src/main/java/com/example/hub/presentation/response/DeliveryManagerResponse.java
  hub/src/main/java/com/example/hub/presentation/response/HubRouteForOrderResponse.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/dto/DeliveryHistoryDto.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/model/DeliveryHistory.java
  order/src/main/java/com/sparta/ch4/delivery/order/infrastructure/client/response/HubRouteForOrderResponse.java
  order/src/main/java/com/sparta/ch4/delivery/order/presentation/response/DeliveryHistoryResponse.java
Labels: fix

#77 Fix: Order 생성 시 에러 catch 통해서 재고 복구 코드 작성
  hub/src/main/java/com/example/hub/presentation/controller/DeliveryManagerController.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/service/OrderService.java
  order/src/main/java/com/sparta/ch4/delivery/order/domain/exception/ErrorCode.java
Labels: fix

#81 Feature/#80 fix error
  hub/src/main/java/com/example/hub/domain/model/BaseEntity.java
  hub/src/main/java/com/example/hub/domain/service/BestRouteDomainService.java
  order/src/main/java/com/sparta/ch4/delivery/order/application/service/OrderService.java
Labels: fix
